### PR TITLE
chore: upgrade @hapi/lab version.

### LINKED ISSUE #5: Fix the CI errors
See: https://travis-ci.org/github/node-casbin/hapi-authz

image

### PR DESCRIPTION
**Pull request by stu01509**
Fix #5 
Upgrade the @hapi/lab version to 24.0.0.
I guess the old version didn't support Node.js 15.0.1.

image

### CODE REVIEW

**Comment by hsluoyz** [comment]
lgtm

**Comment by hsluoyz** [comment]
@stu01509 oh, I forgot one thing just after merging. Did you update the lock file?

**Comment by hsluoyz** [comment]
I have reverted the change. Please make a new PR.

**Comment by stu01509** [comment]
@hsluoyz Ok I created the new PR #7

**Pull request merged**
